language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install future
  - pip install .
# command to run tests
script:
  - python examples/plot_all_styles.py
